//! Core type definitions for NIMon

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Device types supported by NIMon
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DeviceType {
    Daq,
    Pxi,
    CDaq,
    Visa,
    Xnet,
    Gpib,
    PowerSupply,
}

impl std::fmt::Display for DeviceType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            DeviceType::Daq => write!(f, "daq"),
            DeviceType::Pxi => write!(f, "pxi"),
            DeviceType::CDaq => write!(f, "cdaq"),
            DeviceType::Visa => write!(f, "visa"),
            DeviceType::Xnet => write!(f, "xnet"),
            DeviceType::Gpib => write!(f, "gpib"),
            DeviceType::PowerSupply => write!(f, "power_supply"),
        }
    }
}

/// Health status of a device
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum HealthStatus {
    Healthy,
    Warning,
    Error,
    Offline,
}

impl std::fmt::Display for HealthStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HealthStatus::Healthy => write!(f, "healthy"),
            HealthStatus::Warning => write!(f, "warning"),
            HealthStatus::Error => write!(f, "error"),
            HealthStatus::Offline => write!(f, "offline"),
        }
    }
}

/// Edge node status
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EdgeStatus {
    Online,
    Offline,
    Degraded,
}

impl std::fmt::Display for EdgeStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EdgeStatus::Online => write!(f, "online"),
            EdgeStatus::Offline => write!(f, "offline"),
            EdgeStatus::Degraded => write!(f, "degraded"),
        }
    }
}

/// Alert severity levels
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Info,
    Warning,
    Critical,
}

/// Metric value types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MetricValue {
    Float(f64),
    Integer(i64),
    String(String),
    Boolean(bool),
}

/// A device discovered or managed by NIMon
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Device {
    pub id: String,
    pub edge_id: String,
    pub device_name: String,
    pub device_type: DeviceType,
    pub model: Option<String>,
    pub serial_number: Option<String>,
    pub firmware_version: Option<String>,
    pub driver_version: Option<String>,
    pub ip_address: Option<String>,
    pub slot: Option<i32>,
    pub chassis: Option<String>,
}

/// Current status of a device
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeviceStatus {
    pub device_id: String,
    pub status: HealthStatus,
    pub last_poll: DateTime<Utc>,
    pub metrics: HashMap<String, MetricValue>,
    pub error_message: Option<String>,
    pub error_count: i32,
    pub uptime_seconds: i64,
}

/// An edge node in the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdgeNode {
    pub id: String,
    pub name: String,
    pub hostname: Option<String>,
    pub ip_address: Option<String>,
    pub last_seen: Option<DateTime<Utc>>,
    pub status: EdgeStatus,
}

/// A metric data point
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricPoint {
    pub device_id: String,
    pub timestamp: DateTime<Utc>,
    pub metric_name: String,
    pub metric_value: f64,
}

/// Prediction types
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PredictionType {
    Overheating,
    ConnectionFailure,
    PowerSupplyFailure,
    BusDegradation,
    FirmwareIssue,
    Custom(String),
}

/// A prediction generated by the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Prediction {
    pub id: i64,
    pub device_id: String,
    pub edge_id: String,
    pub prediction_type: PredictionType,
    pub probability: f64,
    pub eta_minutes: Option<i32>,
    pub status: PredictionStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PredictionStatus {
    Active,
    Confirmed,
    Dismissed,
}

/// An alert in the system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Alert {
    pub id: i64,
    pub device_id: Option<String>,
    pub edge_id: Option<String>,
    pub rule_name: String,
    pub severity: Severity,
    pub message: String,
    pub status: AlertStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AlertStatus {
    Pending,
    Sent,
    Acknowledged,
    Resolved,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_device_type_serde() {
        let dt = DeviceType::Daq;
        let json = serde_json::to_string(&dt).unwrap();
        assert_eq!(json, "\"daq\"");
        let parsed: DeviceType = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, dt);
    }

    #[test]
    fn test_health_status_display() {
        assert_eq!(HealthStatus::Healthy.to_string(), "healthy");
        assert_eq!(HealthStatus::Warning.to_string(), "warning");
    }
}
