[package]
name = "nimon-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
anyhow = "1"
